# Generated by Django 4.0.4 on 2023-05-20 22:38

import django.contrib.auth.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'Bitcora',
                'ordering': ['-fecha'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Llanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('existencia', models.IntegerField(default=0, verbose_name='Existencia')),
                ('costo_promedio_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo Promedio Pesos')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('subtipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subtipo')),
                ('capas', models.IntegerField(default=0, verbose_name='Capas')),
                ('precio_especia_llantashop_pago_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Especia LLANTASHOP pago Efectivo')),
                ('msi_3', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='3 MSI')),
                ('msi_6', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='6 MSI')),
                ('msi_9', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='9 MSI')),
                ('msi_12', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='12 MSI')),
                ('msi_18', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='18 MSI')),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Envio')),
                ('utilidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Utilidad')),
                ('afiliado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Afiliado')),
                ('actualizado', models.IntegerField(default=1, verbose_name='Actualizado en el proceso de extracción')),
                ('ancho', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ancho')),
                ('alto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alto')),
                ('rin', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rin')),
                ('radial', models.IntegerField(default=0, verbose_name='Radial')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Llanta',
                'verbose_name_plural': 'Llantas',
                'db_table': 'Llanta',
                'ordering': ['producto_clave'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='MensajePicky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('message_in', models.CharField(max_length=255, verbose_name='Mensage in')),
                ('message_in_raw', models.CharField(max_length=255, verbose_name='Mensaje in raw')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensaje')),
                ('application', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aplicación')),
                ('tipo', models.CharField(default=2, max_length=255, verbose_name='Type')),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unique id')),
                ('quoted', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quoted')),
                ('estatus_mensaje', models.IntegerField(choices=[(0, 'Terminado'), (1, 'Activo')], default=1, verbose_name='Estatus del mensaje')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel de pregunta')),
                ('opcion1', models.JSONField(blank=True, null=True, verbose_name='Acción')),
                ('opcion2', models.JSONField(blank=True, null=True, verbose_name='Bien')),
                ('opcion3', models.JSONField(blank=True, null=True, verbose_name='Estado')),
                ('opcion4', models.JSONField(blank=True, null=True, verbose_name='Municipio')),
                ('opcion5', models.JSONField(blank=True, null=True, verbose_name='Bien seleccionado')),
            ],
            options={
                'verbose_name': 'Mensaje picky',
                'verbose_name_plural': 'Mensajes picky',
                'db_table': 'MensajePicky',
                'ordering': ['number', '-fecha_alta'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
